namespace ForgeCore.Auth.Tests.Domain;

public class AccountTest
{
    [Fact]
    public void Create_Should_Assign_Id()
    {
        // Arrange
        var account = AccountFactory.Create();

        // Assert
        account.Id.Should().NotBeEmpty("because the account id is automatically generated by the constructor");
    }

    [Fact]
    public void ChangeDisplayName_Should_Update_Name()
    {
        // Arrange
        var account = AccountFactory.Create();

        // Act
        account.UpdateDisplayName(newDisplayName: "real_account");

        // Assert
        account.DisplayName.Should().Be("real_account", "because the display name should be the one written on the update method");
    }

    [Fact]
    public void AddProvider_Should_Add_New_Provider()
    {
        // Arrange
        var account = AccountFactory.Create();
        var provider = AuthProviderFactory.Create();

        // Act
        account.LinkProvider(provider);

        // Assert
        account.AuthProviders.First().Should().Be(provider);
    }

    [Fact]
    public void Provider_Should_Assign_LinkedDate_When_Adding_Provider()
    {
        // Arrange
        var account = AccountFactory.Create();
        var provider = AuthProviderFactory.Create();

        // Act
        account.LinkProvider(provider);

        // Assert
        account.AuthProviders.First().LinkedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(1));
    }
}
