services:
  postgres:
    image: postgres:18
    container_name: forgecore-postgres
    restart: always
    environment:
      POSTGRES_USER: forgecore
      POSTGRES_PASSWORD: forgecore
      POSTGRES_DB: forgecore
    ports:
      - "5432:5432"
    volumes:
      - forgecore_pgdata:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: forgecore-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  forgecore_pgdata: